const invitees = [
  { id: 1, name: 'Danci Crina', fromWho: 'groom' },
  { id: 2, name: 'Danci Andrei', fromWho: 'groom' },
  { id: 3, name: 'Danci Mariana', fromWho: 'groom' },
  { id: 4, name: 'Danci Vasile', fromWho: 'groom' },
  { id: 5, name: 'Aurelia Vișovan', fromWho: 'groom' },
  { id: 6, name: 'Can Çakmur', fromWho: 'groom', notes: 'prietenul Aureliei Vișovan' },
  { id: 7, name: 'Iulian Mîcnea', fromWho: 'groom' },
  { id: 8, name: 'Diana Mîcnea', fromWho: 'groom', notes: 'prietena lui Iulian Mîcnea' },
  { id: 9, name: 'Ardelean Ramona', fromWho: 'groom' },
  { id: 10, name: 'Ardelean Petrică', fromWho: 'groom' },
  { id: 11, name: 'Doina Balasz', fromWho: 'groom' },
  { id: 12, name: 'Radu Ilnițchi', fromWho: 'groom', notes: 'soțul Doinei Balasz' },
  { id: 13, name: 'Paul Balasz', fromWho: 'groom' },
  { id: 14, name: 'Robert Balasz', fromWho: 'groom' },
  { id: 15, name: 'Vasi Teleptean', fromWho: 'groom' },
  { id: 16, name: 'Vasi Teleptean - logodnică', fromWho: 'groom' },
  { id: 17, name: 'Hajdu Romina', fromWho: 'groom', notes: '"Romina Carpiuc"' },
  { id: 18, name: 'Hajdu Istvan', fromWho: 'groom' },
  { id: 19, name: 'Pr. Ardelean Cornel', fromWho: 'groom' },
  { id: 20, name: 'Ardelean Niculina', fromWho: 'groom' },
  { id: 21, name: 'Haidu Romulus (Romi)', fromWho: 'groom' },
  { id: 22, name: 'Haidu Diana', fromWho: 'groom' },
  { id: 23, name: 'Haidu Luca', fromWho: 'groom', notes: 'copil cls 5-a' },
  { id: 24, name: 'Basanciuc Ovidiu', fromWho: 'groom' },
  { id: 25, name: 'Basanciuc Ramona', fromWho: 'groom' },
  { id: 26, name: 'Mursa Cătălin', fromWho: 'groom' },
  { id: 27, name: 'Mursa (Turcan) Valentina', fromWho: 'groom' },
  { id: 28, name: 'Spiridon Iulian Marian', fromWho: 'groom' },
  { id: 29, name: 'Spiridon Ionela', fromWho: 'groom', notes: '"Chifor Ionela"' },
  { id: 30, name: 'Gelu Godjea', fromWho: 'groom' },
  { id: 31, name: 'Flavia Godjea', fromWho: 'groom' },
  {
    id: 97,
    name: 'Timoftoaie Georgiana',
    notes: '',
  },
  {
    id: 98,
    name: 'Timoftoaie Petru',
    notes: '',
  },
  {
    id: 99,
    name: 'Timoftoaie Leonardo & Iustin',
    notes: '10 ani / 3 ani',
  },
  {
    id: 100,
    name: 'Mirabela Gherasim',
    notes: '',
  },
  {
    id: 101,
    name: 'Carcea Ionuț',
    notes: 'prietenul Mirabelei Gherasim',
  },
  {
    id: 102,
    name: 'Andreea Țăruș',
    notes: '',
  },
  {
    id: 103,
    name: 'Ilie Vieru',
    notes: 'prietenul Andreei Țăruș',
  },
  {
    id: 104,
    name: 'Alexandra Ciobanu',
    notes: '"Alexandra Manolache"',
  },
  {
    id: 105,
    name: 'Gheorghiță Ciobanu',
    notes: '',
  },
  {
    id: 106,
    name: 'Daniel Roșca',
    notes: '',
  },
  {
    id: 107,
    name: 'Angheluță Teodora',
    notes: 'iubita lui Daniel Roșca',
  },
  {
    id: 108,
    name: 'Vrînceanu George',
    notes: '',
  },
  {
    id: 109,
    name: 'Baroi Arianna',
    notes: 'iubita lui Vrînceanu George',
  },
  {
    id: 110,
    name: 'Bogdan Iacob',
    notes: '',
  },
  {
    id: 111,
    name: 'Lupu Maria',
    notes: 'iubita lui Bogdan Iacob',
  },
  {
    id: 114,
    name: 'Lipovanu Dorin',
    notes: 'fratele mamei miresei',
  },
  {
    id: 116,
    name: 'Lipovanu Cristina',
    notes: '+ copil Iustin 3 ani',
  },
  {
    id: 117,
    name: 'Iuliana Constantiniu',
    notes: '"Coca Marțin"',
  },
  {
    id: 118,
    name: 'Tudor Constantiniu',
    notes: '',
  },
  {
    id: 121,
    name: 'Valerica Lucan',
    notes: '',
  },
  {
    id: 122,
    name: 'Costel Cilof',
    notes: 'iubitul Valericăi Lucan',
  },
  {
    id: 123,
    name: 'Gelu Călin',
    notes: '',
  },
  {
    id: 124,
    name: 'Valentina Călin',
    notes: '',
  },
  {
    id: 125,
    name: 'Elena Marțin',
    notes: '',
  },
  {
    id: 126,
    name: 'Alexandra Lucan',
    notes: '',
  },
  {
    id: 127,
    name: 'Bodea Andrei Ionuț',
    notes: 'iubitul Alexandrei Lucan',
  },
  {
    id: 128,
    name: 'Daniel Lucan',
    notes: '',
  },
  {
    id: 129,
    name: 'Bazga Elena Petronela',
    notes: 'iubita lu Daniel Lucan',
  },
  {
    id: 130,
    name: 'Lucan Lenuța',
    notes: '',
  },
  {
    id: 131,
    name: 'Lucan Petrișor',
    notes: '',
  },
  {
    id: 132,
    name: 'Gabi Marțin',
    notes: '',
  },
  {
    id: 133,
    name: 'Călina Marțin',
    notes: '',
  },
  {
    id: 134,
    name: 'Amărculesei Lavinia',
    notes: '',
  },
  {
    id: 135,
    name: 'Amărculesei Lavinia - iubit',
    notes: '',
  },
  {
    id: 136,
    name: 'Iuliana Țuțuianu (Axinte)',
    notes: '',
  },
  {
    id: 137,
    name: 'Ovidiu Țuțuianu',
    notes: '',
  },
  {
    id: 138,
    name: 'Mălina Apopei',
    notes: '',
  },
  {
    id: 139,
    name: 'Marius Apopei',
    notes: '',
  },
  {
    id: 140,
    name: 'Rebegia Raluca',
    notes: '"Raluca Pavel"',
  },
  {
    id: 141,
    name: 'Rebegia Alin',
    notes: '',
  },
  {
    id: 142,
    name: 'Gabriela Mandric',
    notes: '"Gabi Andrioaie"',
  },
  {
    id: 143,
    name: 'Cătălin Mandric',
    notes: '',
  },
  {
    id: 144,
    name: 'Alexandru Archip',
    notes: '',
  },
  {
    id: 145,
    name: 'Cristina Archip',
    notes: '',
  },
  {
    id: 146,
    name: 'Luca Petrică',
    notes: '',
  },
  {
    id: 147,
    name: 'Luca Marinela',
    notes: '',
  },
  {
    id: 148,
    name: 'Anechitoaie Cristian',
    notes: '',
  },
  {
    id: 149,
    name: 'Anechitoaie Mariana',
    notes: '',
  },
  {
    id: 150,
    name: 'Galbin Gheorghe',
    notes: '',
  },
  {
    id: 151,
    name: 'Galbin Anișoara',
    notes: '',
  },
  {
    id: 152,
    name: 'Mihaela Mătase',
    notes: '',
  },
  {
    id: 153,
    name: 'Puiu Mătase',
    notes: '',
  },
  {
    id: 156,
    name: 'Cristina Marinela Balmuș',
    notes: '"Cristina Eșanu"',
  },
  {
    id: 157,
    name: 'Ionuț Balmuș',
    notes: 'soț Cristina Eșanu',
  },
  {
    id: 158,
    name: 'Mihaela Chelciuc',
    notes: '',
  },
  {
    id: 159,
    name: 'Agache Bogdan',
    notes: 'iubitul Mihaelei Chelciuc',
  },
];

export default invitees;
